version: "3.4"

services:
    trackmeal:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        environment:
          ConnectionStrings:DefaultConnection: "Server=db;Database=TrackmealDb;User=sa;Password=${SA_PASSWORD};"
          InitialAdminPassword: "${ADMIN_PASSWORD}"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        environment:
          SA_PASSWORD: ${SA_PASSWORD}
          ACCEPT_EULA: "Y"
